Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/CPO/train_cpo_custom.py", line 104, in <module>
    "constrained_rl": args.constrained_rl,
NameError: name 'args' is not defined
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/CPO/train_cpo_custom.py", line 104, in <module>
    "constrained_rl": args.constrained_rl,
NameError: name 'args' is not defined
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/CPO/train_cpo_custom.py", line 104, in <module>
    "constrained_rl": args.constrained_rl,
NameError: name 'args' is not defined
srun: error: airl.ist.berkeley.edu: task 0: Exited with exit code 1
srun: error: ddpg.ist.berkeley.edu: task 0: Exited with exit code 1
srun: error: gail.ist.berkeley.edu: task 0: Exited with exit code 1
