wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.16.1 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20240104_200031-lz7wsiu7
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run ruby-sun-1
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/New-PPOL-SpeedLimit%3D10000
wandb: üöÄ View run at https://wandb.ai/ecrl/New-PPOL-SpeedLimit%3D10000/runs/lz7wsiu7
wandb: wandb version 0.16.1 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20240104_200031-y0gyq755
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run stoic-smoke-2
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/New-PPOL-SpeedLimit%3D10000
wandb: üöÄ View run at https://wandb.ai/ecrl/New-PPOL-SpeedLimit%3D10000/runs/y0gyq755
wandb: wandb version 0.16.1 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20240104_200031-ru3qqbsp
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run dashing-rain-3
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/New-PPOL-SpeedLimit%3D10000
wandb: üöÄ View run at https://wandb.ai/ecrl/New-PPOL-SpeedLimit%3D10000/runs/ru3qqbsp
Using cpu device
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 125, in <module>
    train()
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 102, in train
    agent.learn(total_timesteps=args.total_timesteps, callback=callback, reset_num_timesteps=False)
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/ppol/ppol.py", line 405, in learn
    result = super().learn(
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/on_policy_algorithm.py", line 572, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/on_policy_algorithm.py", line 522, in collect_rollouts
    rollout_buffer.add(
TypeError: add() got an unexpected keyword argument 'costs'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
Using cpu device
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 125, in <module>
    train()
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 102, in train
    agent.learn(total_timesteps=args.total_timesteps, callback=callback, reset_num_timesteps=False)
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/ppol/ppol.py", line 405, in learn
    result = super().learn(
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/on_policy_algorithm.py", line 572, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/on_policy_algorithm.py", line 522, in collect_rollouts
    rollout_buffer.add(
TypeError: add() got an unexpected keyword argument 'costs'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: wandb version 0.16.1 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20240105_040031-eauii385
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run balmy-firebrand-4
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/New-PPOL-SpeedLimit%3D10000
wandb: üöÄ View run at https://wandb.ai/ecrl/New-PPOL-SpeedLimit%3D10000/runs/eauii385
Using cpu device
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 125, in <module>
    train()
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 102, in train
    agent.learn(total_timesteps=args.total_timesteps, callback=callback, reset_num_timesteps=False)
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/ppol/ppol.py", line 405, in learn
    result = super().learn(
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/on_policy_algorithm.py", line 572, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/on_policy_algorithm.py", line 522, in collect_rollouts
    rollout_buffer.add(
TypeError: add() got an unexpected keyword argument 'costs'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
Using cpu device
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 125, in <module>
    train()
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 102, in train
    agent.learn(total_timesteps=args.total_timesteps, callback=callback, reset_num_timesteps=False)
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/ppol/ppol.py", line 405, in learn
    result = super().learn(
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/on_policy_algorithm.py", line 572, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/on_policy_algorithm.py", line 522, in collect_rollouts
    rollout_buffer.add(
TypeError: add() got an unexpected keyword argument 'costs'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: ERROR Error while calling W&B API: An internal error occurred. Please contact support. (<Response [500]>)
wandb: ERROR Error while calling W&B API: An internal error occurred. Please contact support. (<Response [500]>)
wandb: 
wandb: Run history:
wandb:       cost ‚ñÅ
wandb: is_success ‚ñÅ
wandb:     reward ‚ñÅ
wandb: 
wandb: Run summary:
wandb:       cost 0
wandb: is_success 0
wandb:     reward -0.31948
wandb: 
wandb: üöÄ View run ruby-sun-1 at: https://wandb.ai/ecrl/New-PPOL-SpeedLimit%3D10000/runs/lz7wsiu7
wandb: Synced 5 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240104_200031-lz7wsiu7/logs
wandb: ERROR Error while calling W&B API: An internal error occurred. Please contact support. (<Response [500]>)
wandb: 
wandb: Run history:
wandb:       cost ‚ñÅ
wandb: is_success ‚ñÅ
wandb:     reward ‚ñÅ
wandb: 
wandb: Run summary:
wandb:       cost 0
wandb: is_success 0
wandb:     reward -0.54968
wandb: 
wandb: üöÄ View run balmy-firebrand-4 at: https://wandb.ai/ecrl/New-PPOL-SpeedLimit%3D10000/runs/eauii385
wandb: Synced 5 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240105_040031-eauii385/logs
srun: error: ddpg.ist.berkeley.edu: task 0: Exited with exit code 1
wandb: 
wandb: Run history:
wandb:       cost ‚ñÅ
wandb: is_success ‚ñÅ
wandb:     reward ‚ñÅ
wandb: 
wandb: Run summary:
wandb:       cost 0
wandb: is_success 0
wandb:     reward -0.37655
wandb: 
wandb: üöÄ View run dashing-rain-3 at: https://wandb.ai/ecrl/New-PPOL-SpeedLimit%3D10000/runs/ru3qqbsp
wandb: Synced 5 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240104_200031-ru3qqbsp/logs
srun: error: airl.ist.berkeley.edu: task 0: Exited with exit code 1
wandb: 
wandb: Run history:
wandb:       cost ‚ñÅ
wandb: is_success ‚ñÅ
wandb:     reward ‚ñÅ
wandb: 
wandb: Run summary:
wandb:       cost 0
wandb: is_success 0
wandb:     reward -0.2494
wandb: 
wandb: üöÄ View run stoic-smoke-2 at: https://wandb.ai/ecrl/New-PPOL-SpeedLimit%3D10000/runs/y0gyq755
wandb: Synced 5 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240104_200031-y0gyq755/logs
srun: error: dqn.ist.berkeley.edu: task 0: Exited with exit code 1
srun: error: gail.ist.berkeley.edu: task 0: Exited with exit code 1
srun: Job 115876 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for StepId=115876.4
wandb: Currently logged in as: mason-nakamura1 (ecrl). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.16.1 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /nas/ucb/mason/ethically-compliant-rl/wandb/run-20240105_040231-rf2amy1h
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run fearless-flower-5
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ecrl/New-PPOL-SpeedLimit%3D10000
wandb: üöÄ View run at https://wandb.ai/ecrl/New-PPOL-SpeedLimit%3D10000/runs/rf2amy1h
Using cpu device
Traceback (most recent call last):
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 125, in <module>
    train()
  File "/nas/ucb/mason/ethically-compliant-rl/.venv/lib/python3.9/site-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/nas/ucb/mason/ethically-compliant-rl/PPOL_New/train_ppol_high_limit.py", line 102, in train
    agent.learn(total_timesteps=args.total_timesteps, callback=callback, reset_num_timesteps=False)
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/ppol/ppol.py", line 405, in learn
    result = super().learn(
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/on_policy_algorithm.py", line 572, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
  File "/nas/ucb/mason/ethically-compliant-rl/stable_baselines3/stable_baselines3/common/on_policy_algorithm.py", line 522, in collect_rollouts
    rollout_buffer.add(
TypeError: add() got an unexpected keyword argument 'costs'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: 
wandb: Run history:
wandb:       cost ‚ñÅ
wandb: is_success ‚ñÅ
wandb:     reward ‚ñÅ
wandb: 
wandb: Run summary:
wandb:       cost 0
wandb: is_success 0
wandb:     reward -0.42676
wandb: 
wandb: üöÄ View run fearless-flower-5 at: https://wandb.ai/ecrl/New-PPOL-SpeedLimit%3D10000/runs/rf2amy1h
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240105_040231-rf2amy1h/logs
srun: error: airl.ist.berkeley.edu: task 0: Exited with exit code 1
